#!/bin/sh 


### BEGIN INIT INFO
# Provides:          tcptouartd
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the tcptouartd.
### END INIT INFO

my_start_service() {
	/bin/tcptouart.sh &
	#/bin/o2oservice.sh &
}
my_stop_service() {
        echo "stop tcptouart server"
        killall tcptouart.sh tcptouart
        #killall o2oservice.sh
}

case "$1" in
start)
	my_start_service
	;;

stop)
	my_stop_service
	;;
esac

exit 0

